spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pus?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    port: 6379
    host: localhost

  profiles:
    active: s3

# HS256????, 32byte ?? secret key ??
# echo -n 'thisisstudymatcingprojectnamedpus'
jwt:
  secret: dGhpc2lzc3R1ZHltYXRjaGluZ3Byb2plY3RuYW1lZHB1cw==
